# Generated by Django 2.2.2 on 2020-06-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍2', 'verbose_name_plural': '书籍2'},
        ),
    ]
