# Generated by Django 2.2.2 on 2020-06-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0002_auto_20200602_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authordetail',
            old_name='moobile',
            new_name='mobile',
        ),
    ]
