# Generated by Django 2.2.2 on 2020-06-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0003_auto_20200602_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='author',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail', to='api_v3.Author'),
        ),
    ]
